apiVersion: v1
kind: Service
metadata:
  name: safe-settings-svc
  namespace: safe-settings
  labels:
    app: safe-settings
spec:
  type: NodePort
  ports:
    - name: safe-settings-port
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30300
  selector:
    app: safe-settings
